@Api_HostAddress = http://localhost:5024
@orderId = {{Create.response.body.orderId}}

### Criar pedido standard
# @name Create
POST {{Api_HostAddress}}/v1/orders
Content-Type: application/json
Idempotency-Key: {{$guid}}

{
  "type": 0,
  "items": [
    { "description": "Camiseta", "quantity": 2, "unitPrice": 49.90 },
    { "description": "Boné", "quantity": 1, "unitPrice": 29.90 }
  ]
}

### Criar pedido express (acréscimo de 15%)
POST {{Api_HostAddress}}/v1/orders
Content-Type: application/json

{
  "type": 1,
  "items": [
    { "description": "Tênis", "quantity": 1, "unitPrice": 199.90 }
  ]
}

### Criar pedido subscription (desconto de 10%)
POST {{Api_HostAddress}}/v1/orders
Content-Type: application/json

{
  "type": 2,
  "items": [
    { "description": "Mochila", "quantity": 1, "unitPrice": 150.00 }
  ]
}

### Consultar pedido
GET {{Api_HostAddress}}/v1/orders/{{orderId}}
Accept: application/json

### Atualizar item do pedido
PUT {{Api_HostAddress}}/v1/orders/{{orderId}}/items/<ITEM_ID>
Content-Type: application/json

{
  "description": "Camiseta G",
  "quantity": 3,
  "unitPrice": 49.90
}

### Remover item do pedido
DELETE {{Api_HostAddress}}/v1/orders/{{orderId}}/items/<ITEM_ID>
